// lib/learnResources.js
// Curated learning library for MERIDIAN LEARN (/learn).
// Each item: { name, provider, type, level, group, url, blurb, free }
//   level : Foundations | Intermediate | Advanced | All
//   group : display section (Foundations, Intermediate, Advanced, Daily reads, Tools & data, Podcasts)
//   type  : Book | Course | Newsletter | Reference | Community | Tool | Podcast | Channel | Blog | Credential
// Nothing here is auto-published: this file is reviewed before it ships.

export const GROUPS = [
  'Foundations',
  'Intermediate',
  'Advanced',
  'Daily reads',
  'Tools & data',
  'Podcasts',
];

export const TYPES = [
  'Book', 'Course', 'Newsletter', 'Reference', 'Community',
  'Tool', 'Podcast', 'Channel', 'Blog', 'Credential',
];

export const RESOURCES = [
  // -- FOUNDATIONS ----------------------------------------------------------
  {
    name: 'Investopedia',
    provider: 'Investopedia',
    type: 'Reference',
    level: 'Foundations',
    group: 'Foundations',
    url: 'https://www.investopedia.com/',
    free: true,
    blurb: 'The free encyclopedia of finance. Look up any term you meet in a deal or on the tape, from EBITDA to mezzanine, with clear worked examples.',
  },
  {
    name: 'Finance & Capital Markets',
    provider: 'Khan Academy',
    type: 'Course',
    level: 'Foundations',
    group: 'Foundations',
    url: 'https://www.khanacademy.org/economics-finance-domain/core-finance',
    free: true,
    blurb: 'Free, plain-English video lessons that build the mental model: interest, bonds, equities, options and how capital markets actually fit together.',
  },
  {
    name: 'Corporate Finance Institute (CFI)',
    provider: 'CFI',
    type: 'Course',
    level: 'Foundations',
    group: 'Foundations',
    url: 'https://corporatefinanceinstitute.com/',
    free: false,
    blurb: 'Structured courses in accounting, finance and modeling, plus the FMVA certification. A broad, beginner-friendly on-ramp used even by corporate training desks.',
  },
  {
    name: 'Aswath Damodaran (YouTube)',
    provider: 'NYU Stern',
    type: 'Channel',
    level: 'Foundations',
    group: 'Foundations',
    url: 'https://www.youtube.com/channel/UCLvnJL8htRR1T9cbSccaoVw',
    free: true,
    blurb: 'The "Dean of Valuation" posts his full NYU corporate-finance and valuation lectures for free. The single best place to learn valuation properly.',
  },
  {
    name: 'The Little Book of Valuation',
    provider: 'Aswath Damodaran',
    type: 'Book',
    level: 'Foundations',
    group: 'Foundations',
    url: 'https://www.wiley.com/en-us/The+Little+Book+of+Valuation%3A+How+to+Value+a+Company%2C+Pick+a+Stock+and+Profit-p-9781118004777',
    free: false,
    blurb: 'The most approachable way in to valuation. Short, practical and honest about where the numbers come from and where they break.',
  },
  {
    name: 'The Intelligent Investor',
    provider: 'Benjamin Graham',
    type: 'Book',
    level: 'Foundations',
    group: 'Foundations',
    url: 'https://www.harpercollins.com/products/the-intelligent-investor-rev-ed-benjamin-graham',
    free: false,
    blurb: 'The value-investing classic that shaped Warren Buffett. Timeless on risk, "Mr. Market", and the difference between price and value.',
  },
  {
    name: 'Mergers & Inquisitions',
    provider: 'Brian DeChesare',
    type: 'Blog',
    level: 'Foundations',
    group: 'Foundations',
    url: 'https://mergersandinquisitions.com/',
    free: true,
    blurb: 'The go-to blog for how investment-banking and private-equity careers actually work: roles, recruiting, exit options and what the job is really like.',
  },

  // -- INTERMEDIATE ---------------------------------------------------------
  {
    name: 'Investment Banking: Valuation, LBOs, M&A',
    provider: 'Rosenbaum & Pearl',
    type: 'Book',
    level: 'Intermediate',
    group: 'Intermediate',
    url: 'https://www.wiley.com/en-us/Investment+Banking%3A+Valuation%2C+LBOs%2C+M%26A%2C+and+IPOs-p-9781119706182',
    free: false,
    blurb: 'The industry bible. Step-by-step through comparable companies, precedent transactions, DCF and LBO analysis, the way analysts are trained to build them.',
  },
  {
    name: 'Wall Street Prep',
    provider: 'Wall Street Prep',
    type: 'Course',
    level: 'Intermediate',
    group: 'Intermediate',
    url: 'https://www.wallstreetprep.com/',
    free: false,
    blurb: 'Hands-on financial-modeling training used to onboard analysts at most bulge-bracket banks. Practical Excel and real-world case studies, not theory.',
  },
  {
    name: 'Breaking Into Wall Street (BIWS)',
    provider: 'Brian DeChesare',
    type: 'Course',
    level: 'Intermediate',
    group: 'Intermediate',
    url: 'https://breakingintowallstreet.com/',
    free: false,
    blurb: 'Modeling courses built around real deals and interview case studies. Strong if your goal is landing and surviving an IB, PE or equity-research role.',
  },
  {
    name: 'Macabacus',
    provider: 'Macabacus',
    type: 'Reference',
    level: 'Intermediate',
    group: 'Intermediate',
    url: 'https://macabacus.com/',
    free: true,
    blurb: 'Best-practice reference for Excel and financial modeling, plus a widely used productivity add-in. Great for tightening up formatting and model discipline.',
  },
  {
    name: 'Damodaran Online',
    provider: 'NYU Stern',
    type: 'Reference',
    level: 'Intermediate',
    group: 'Intermediate',
    url: 'https://pages.stern.nyu.edu/~adamodar/',
    free: true,
    blurb: 'A treasure chest: free valuation spreadsheets, current industry datasets (betas, margins, cost of capital) and the full valuation class, all downloadable.',
  },
  {
    name: 'Wall Street Oasis',
    provider: 'WSO',
    type: 'Community',
    level: 'Intermediate',
    group: 'Intermediate',
    url: 'https://www.wallstreetoasis.com/',
    free: true,
    blurb: 'The largest finance-careers community: interview guides, compensation data and candid forum threads from people doing the jobs you want.',
  },

  // -- ADVANCED -------------------------------------------------------------
  {
    name: 'Investment Valuation',
    provider: 'Aswath Damodaran',
    type: 'Book',
    level: 'Advanced',
    group: 'Advanced',
    url: 'https://www.wiley.com/en-us/Investment+Valuation%3A+Tools+and+Techniques+for+Determining+the+Value+of+Any+Asset%2C+3rd+Edition-p-9781118130735',
    free: false,
    blurb: 'The deep, comprehensive text on valuing anything, from high-growth tech to distressed and emerging-market assets. The reference professionals return to.',
  },
  {
    name: 'Barbarians at the Gate',
    provider: 'Burrough & Helyar',
    type: 'Book',
    level: 'Advanced',
    group: 'Advanced',
    url: 'https://www.harpercollins.com/products/barbarians-at-the-gate-bryan-burroughjohn-helyar',
    free: false,
    blurb: 'The definitive narrative of the RJR Nabisco leveraged buyout. The best way to feel how ego, leverage and negotiation drive a mega-deal.',
  },
  {
    name: 'King of Capital',
    provider: 'Carey & Morris',
    type: 'Book',
    level: 'Advanced',
    group: 'Advanced',
    url: 'https://www.penguinrandomhouse.com/books/89661/king-of-capital-by-david-carey-and-john-e-morris/',
    free: false,
    blurb: 'The rise of Blackstone and modern private equity. Essential context for how buyout firms raise, deploy and return capital across cycles.',
  },
  {
    name: 'Advanced Valuation (Online Certificate)',
    provider: 'NYU Stern / Damodaran',
    type: 'Course',
    level: 'Advanced',
    group: 'Advanced',
    url: 'https://execed.stern.nyu.edu/products/advanced-valuation-with-aswath-damodaran',
    free: false,
    blurb: 'A 15-week deep course taught by Damodaran himself, taking you from intrinsic to relative to contingent-claim valuation. The paid, guided version.',
  },
  {
    name: 'CFA Program',
    provider: 'CFA Institute',
    type: 'Credential',
    level: 'Advanced',
    group: 'Advanced',
    url: 'https://www.cfainstitute.org/programs/cfa',
    free: false,
    blurb: 'The gold-standard credential for investment analysis and portfolio management. Three rigorous exams that signal serious commitment to the buy side.',
  },
  {
    name: 'Oaktree Memos',
    provider: 'Howard Marks',
    type: 'Reference',
    level: 'Advanced',
    group: 'Advanced',
    url: 'https://www.oaktreecapital.com/insights/memos',
    free: true,
    blurb: "Howard Marks's free memos on cycles, risk and market psychology. Buffett has said he reads them the day they arrive. So should you.",
  },

  // -- DAILY READS ----------------------------------------------------------
  {
    name: 'Money Stuff',
    provider: 'Matt Levine, Bloomberg',
    type: 'Newsletter',
    level: 'All',
    group: 'Daily reads',
    url: 'https://www.bloomberg.com/account/newsletters/money-stuff',
    free: true,
    blurb: 'The best finance newsletter in the world, and free. Matt Levine makes Wall Street, M&A and market plumbing genuinely funny and genuinely clear.',
  },
  {
    name: 'Due Diligence',
    provider: 'Financial Times',
    type: 'Newsletter',
    level: 'All',
    group: 'Daily reads',
    url: 'https://www.ft.com/due-diligence',
    free: false,
    blurb: "The FT's insider briefing on M&A, private equity and dealmaking. The morning read for people who work on transactions.",
  },
  {
    name: 'Axios Pro Rata',
    provider: 'Dan Primack',
    type: 'Newsletter',
    level: 'All',
    group: 'Daily reads',
    url: 'https://www.axios.com/newsletters/axios-pro-rata',
    free: true,
    blurb: "Dan Primack's fast daily brief on deals, venture capital and private equity. Short, sharp and consistently ahead of the pack.",
  },
  {
    name: 'PETITION',
    provider: 'PETITION LLC',
    type: 'Newsletter',
    level: 'Advanced',
    group: 'Daily reads',
    url: 'https://petition.substack.com/',
    free: true,
    blurb: 'The essential read on corporate distress, restructuring and bankruptcy. Irreverent, deeply informed, and early on where the credit stress is building.',
  },

  // -- TOOLS & DATA ---------------------------------------------------------
  {
    name: 'SEC EDGAR',
    provider: 'U.S. SEC',
    type: 'Tool',
    level: 'All',
    group: 'Tools & data',
    url: 'https://www.sec.gov/edgar/search/',
    free: true,
    blurb: 'Every US public filing, free: 10-Ks, 8-Ks, merger proxies and S-1s. Learn to read primary sources instead of second-hand summaries.',
  },
  {
    name: 'Koyfin',
    provider: 'Koyfin',
    type: 'Tool',
    level: 'All',
    group: 'Tools & data',
    url: 'https://www.koyfin.com/',
    free: true,
    blurb: 'A generous free tier for market data, screening and charting. A practical, affordable stand-in for a Bloomberg terminal while you learn.',
  },
  {
    name: 'TradingView',
    provider: 'TradingView',
    type: 'Tool',
    level: 'All',
    group: 'Tools & data',
    url: 'https://www.tradingview.com/',
    free: true,
    blurb: 'Fast, free charting for equities, rates, FX and crypto. Handy for tracking the price action behind the headlines you read here.',
  },
  {
    name: 'Damodaran Datasets',
    provider: 'NYU Stern',
    type: 'Tool',
    level: 'Intermediate',
    group: 'Tools & data',
    url: 'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/data.html',
    free: true,
    blurb: 'Free, regularly updated industry data: betas, margins, cost of capital and multiples by sector. The inputs your valuation models actually need.',
  },

  // -- PODCASTS -------------------------------------------------------------
  {
    name: 'Odd Lots',
    provider: 'Bloomberg',
    type: 'Podcast',
    level: 'All',
    group: 'Podcasts',
    url: 'https://www.bloomberg.com/oddlots',
    free: true,
    blurb: 'Tracy Alloway and Joe Weisenthal unpack whatever is moving markets that week, from commodities to credit, with the people who actually know.',
  },
  {
    name: 'Acquired',
    provider: 'Ben Gilbert & David Rosenthal',
    type: 'Podcast',
    level: 'All',
    group: 'Podcasts',
    url: 'https://www.acquired.fm/',
    free: true,
    blurb: 'Feature-length deep dives into the companies and deals that shaped the economy. Superb for understanding strategy, moats and how value compounds.',
  },
  {
    name: 'Money Stuff: The Podcast',
    provider: 'Bloomberg',
    type: 'Podcast',
    level: 'All',
    group: 'Podcasts',
    url: 'https://www.bloomberg.com/podcasts/series/money-stuff',
    free: true,
    blurb: 'Matt Levine and Katie Greifeld talk through the week in finance weirdness. The audio companion to the newsletter, just as entertaining.',
  },
];
