// lib/learnResources.js
// Curated learning library for MERIDIAN LEARN (/learn).
// Structure by SECTION: Books | Resources | Podcasts | Miscellaneous.
// Each item: { name, provider, type, group, url, blurb, free }
//   group : Books | Resources | Podcasts | Miscellaneous
//   type  : Book | Site | Blog | Channel | Newsletter | Podcast | Tool | Data | Community | Credential
// Editorial rule: only things worth recommending. No paid courses we do not stand behind.
// Growth: the "suggest -> approve" flow appends approved items here after review.

export const GROUPS = ['Books', 'Resources', 'Podcasts', 'Miscellaneous'];

export const RESOURCES = [
  // ============================ BOOKS ============================
  {
    name: 'The Intelligent Investor',
    provider: 'Benjamin Graham',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/The_Intelligent_Investor',
    free: false,
    blurb: 'The value-investing bible that shaped Warren Buffett. Timeless on margin of safety, "Mr. Market", and the gap between price and value.',
  },
  {
    name: 'Security Analysis',
    provider: 'Graham & Dodd',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/Security_Analysis_(book)',
    free: false,
    blurb: 'The 1934 foundation text of fundamental analysis. Dense, demanding and still the deepest treatment of what a security is really worth.',
  },
  {
    name: 'Common Stocks and Uncommon Profits',
    provider: 'Philip A. Fisher',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/Common_Stocks_and_Uncommon_Profits',
    free: false,
    blurb: 'The classic case for growth investing and qualitative research. Fisher on how to judge management, moats and durable competitive advantage.',
  },
  {
    name: 'The Little Book of Valuation',
    provider: 'Aswath Damodaran',
    type: 'Book',
    group: 'Books',
    url: 'https://www.wiley.com/en-us/The+Little+Book+of+Valuation%3A+How+to+Value+a+Company%2C+Pick+a+Stock+and+Profit-p-9781118004777',
    free: false,
    blurb: 'The friendliest way in to valuation. Short and practical, and honest about where the numbers come from and where they break.',
  },
  {
    name: 'Investment Valuation',
    provider: 'Aswath Damodaran',
    type: 'Book',
    group: 'Books',
    url: 'https://www.wiley.com/en-us/Investment+Valuation%3A+Tools+and+Techniques+for+Determining+the+Value+of+Any+Asset%2C+3rd+Edition-p-9781118130735',
    free: false,
    blurb: 'The comprehensive reference on valuing anything, from high-growth tech to distressed assets. The book professionals keep on the desk.',
  },
  {
    name: 'Investment Banking: Valuation, LBOs & M&A',
    provider: 'Rosenbaum & Pearl',
    type: 'Book',
    group: 'Books',
    url: 'https://www.wiley.com/en-us/Investment+Banking%3A+Valuation%2C+LBOs%2C+M%26A%2C+and+IPOs-p-9781119706182',
    free: false,
    blurb: 'The industry standard on comps, precedent transactions, DCF and LBO analysis, laid out the way analysts are actually trained to build them.',
  },
  {
    name: 'Barbarians at the Gate',
    provider: 'Burrough & Helyar',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/Barbarians_at_the_Gate_(book)',
    free: false,
    blurb: 'The definitive story of the RJR Nabisco buyout. The best way to feel how ego, leverage and negotiation drive a mega-deal.',
  },
  {
    name: 'King of Capital',
    provider: 'Carey & Morris',
    type: 'Book',
    group: 'Books',
    url: 'https://www.penguinrandomhouse.com/books/89661/king-of-capital-by-david-carey-and-john-e-morris/',
    free: false,
    blurb: 'The rise of Blackstone and modern private equity. Essential for understanding how buyout firms raise, deploy and return capital across cycles.',
  },
  {
    name: "Liar's Poker",
    provider: 'Michael Lewis',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/Liar%27s_Poker',
    free: false,
    blurb: "Michael Lewis's insider account of 1980s Salomon Brothers. Funny, sharp, and the book that made a generation want to trade bonds.",
  },
  {
    name: 'The Big Short',
    provider: 'Michael Lewis',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/The_Big_Short',
    free: false,
    blurb: 'How a handful of outsiders saw the 2008 mortgage collapse coming. The clearest explanation of CDOs, CDS and structured credit gone wrong.',
  },
  {
    name: 'When Genius Failed',
    provider: 'Roger Lowenstein',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/When_Genius_Failed',
    free: false,
    blurb: 'The rise and fall of Long-Term Capital Management. A masterclass in leverage, model risk and how the smartest people blow up.',
  },
  {
    name: 'More Money Than God',
    provider: 'Sebastian Mallaby',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/More_Money_Than_God',
    free: false,
    blurb: 'The definitive history of hedge funds and the people who built them. Great on strategy, edge, and where returns actually come from.',
  },
  {
    name: 'The Snowball',
    provider: 'Alice Schroeder',
    type: 'Book',
    group: 'Books',
    url: 'https://en.wikipedia.org/wiki/The_Snowball:_Warren_Buffett_and_the_Business_of_Life',
    free: false,
    blurb: 'The authorised life of Warren Buffett. The closest thing to watching how a great capital allocator actually thinks, deal by deal.',
  },

  // ========================== RESOURCES ==========================
  {
    name: 'Damodaran Online',
    provider: 'NYU Stern',
    type: 'Site',
    group: 'Resources',
    url: 'https://pages.stern.nyu.edu/~adamodar/',
    free: true,
    blurb: 'A treasure chest: free valuation spreadsheets, current industry datasets and the full valuation class, all downloadable. The best free finance site online.',
  },
  {
    name: 'Aswath Damodaran (YouTube)',
    provider: 'NYU Stern',
    type: 'Channel',
    group: 'Resources',
    url: 'https://www.youtube.com/channel/UCLvnJL8htRR1T9cbSccaoVw',
    free: true,
    blurb: 'The "Dean of Valuation" posts his full NYU corporate-finance and valuation lectures for free. The single best place to actually learn valuation.',
  },
  {
    name: 'Musings on Markets',
    provider: 'Aswath Damodaran',
    type: 'Blog',
    group: 'Resources',
    url: 'https://aswathdamodaran.blogspot.com/',
    free: true,
    blurb: "Damodaran's long-running blog, where he values the biggest names and market stories of the moment in real time, and shows all his work.",
  },
  {
    name: 'Investopedia',
    provider: 'Investopedia',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.investopedia.com/',
    free: true,
    blurb: 'The free encyclopedia of finance. Look up any term you meet in a deal or on the tape, from EBITDA to mezzanine, with clear worked examples.',
  },
  {
    name: 'Khan Academy: Finance',
    provider: 'Khan Academy',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.khanacademy.org/economics-finance-domain/core-finance',
    free: true,
    blurb: 'Free, plain-English lessons that build the mental model: interest, bonds, equities, options and how the pieces of capital markets fit together.',
  },
  {
    name: 'Mergers & Inquisitions',
    provider: 'Brian DeChesare',
    type: 'Blog',
    group: 'Resources',
    url: 'https://mergersandinquisitions.com/',
    free: true,
    blurb: 'The most candid writing on how investment-banking and private-equity careers really work: roles, recruiting, exits and what the job is like.',
  },
  {
    name: 'Macabacus',
    provider: 'Macabacus',
    type: 'Site',
    group: 'Resources',
    url: 'https://macabacus.com/',
    free: true,
    blurb: 'A free best-practice reference for Excel and financial modeling. The place to tighten up your formatting, structure and model discipline.',
  },
  {
    name: 'Oaktree Memos',
    provider: 'Howard Marks',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.oaktreecapital.com/insights/memos',
    free: true,
    blurb: "Howard Marks's free memos on cycles, risk and market psychology. Buffett has said he reads them the day they arrive. So should you.",
  },

  // ========================== PODCASTS ==========================
  {
    name: 'Odd Lots',
    provider: 'Bloomberg',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.bloomberg.com/oddlots',
    free: true,
    blurb: 'Tracy Alloway and Joe Weisenthal unpack whatever is moving markets that week, from commodities to credit, with the people who actually know.',
  },
  {
    name: 'Acquired',
    provider: 'Gilbert & Rosenthal',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.acquired.fm/',
    free: true,
    blurb: 'Feature-length deep dives into the companies and deals that shaped the economy. Superb on strategy, moats and how value compounds over decades.',
  },
  {
    name: 'Invest Like the Best',
    provider: 'Patrick OShaughnessy',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.joincolossus.com/',
    free: true,
    blurb: 'Long conversations with world-class investors and operators about how they find edge, allocate capital and think about risk.',
  },
  {
    name: 'Founders',
    provider: 'David Senra',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.founderspodcast.com/',
    free: true,
    blurb: 'Deep readings of the biographies of history's great entrepreneurs and capital allocators, distilled into lessons you can use.',
  },
  {
    name: 'Money Stuff: The Podcast',
    provider: 'Bloomberg',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.bloomberg.com/podcasts/series/money-stuff',
    free: true,
    blurb: 'Matt Levine and Katie Greifeld talk through the week in finance weirdness. The audio companion to the newsletter, just as entertaining.',
  },

  // ======================== MISCELLANEOUS ========================
  {
    name: 'Money Stuff',
    provider: 'Matt Levine, Bloomberg',
    type: 'Newsletter',
    group: 'Miscellaneous',
    url: 'https://www.bloomberg.com/account/newsletters/money-stuff',
    free: true,
    blurb: 'The best finance newsletter in the world, and free. Matt Levine makes Wall Street, M&A and market plumbing genuinely funny and genuinely clear.',
  },
  {
    name: 'FT Due Diligence',
    provider: 'Financial Times',
    type: 'Newsletter',
    group: 'Miscellaneous',
    url: 'https://www.ft.com/due-diligence',
    free: false,
    blurb: "The FT's insider briefing on M&A, private equity and dealmaking. The morning read for people who work on transactions.",
  },
  {
    name: 'Axios Pro Rata',
    provider: 'Dan Primack',
    type: 'Newsletter',
    group: 'Miscellaneous',
    url: 'https://www.axios.com/newsletters/axios-pro-rata',
    free: true,
    blurb: "Dan Primack's fast daily brief on deals, venture capital and private equity. Short, sharp and consistently ahead of the pack.",
  },
  {
    name: 'PETITION',
    provider: 'PETITION LLC',
    type: 'Newsletter',
    group: 'Miscellaneous',
    url: 'https://petition.substack.com/',
    free: true,
    blurb: 'The essential read on corporate distress, restructuring and bankruptcy. Irreverent, deeply informed, and early on where credit stress is building.',
  },
  {
    name: 'SEC EDGAR',
    provider: 'U.S. SEC',
    type: 'Tool',
    group: 'Miscellaneous',
    url: 'https://www.sec.gov/edgar/search/',
    free: true,
    blurb: 'Every US public filing, free: 10-Ks, 8-Ks, merger proxies and S-1s. Learn to read the primary source instead of the second-hand summary.',
  },
  {
    name: 'Koyfin',
    provider: 'Koyfin',
    type: 'Tool',
    group: 'Miscellaneous',
    url: 'https://www.koyfin.com/',
    free: true,
    blurb: 'A generous free tier for market data, screening and charting. A practical stand-in for a Bloomberg terminal while you learn.',
  },
  {
    name: 'TradingView',
    provider: 'TradingView',
    type: 'Tool',
    group: 'Miscellaneous',
    url: 'https://www.tradingview.com/',
    free: true,
    blurb: 'Fast, free charting for equities, rates, FX and crypto. Handy for tracking the price action behind the headlines you read here.',
  },
  {
    name: 'Damodaran Datasets',
    provider: 'NYU Stern',
    type: 'Data',
    group: 'Miscellaneous',
    url: 'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/data.html',
    free: true,
    blurb: 'Free, regularly updated industry data: betas, margins, cost of capital and multiples by sector. The inputs your valuation models actually need.',
  },
  {
    name: 'Wall Street Oasis',
    provider: 'WSO',
    type: 'Community',
    group: 'Miscellaneous',
    url: 'https://www.wallstreetoasis.com/',
    free: true,
    blurb: 'The largest finance-careers community: interview guides, compensation data and candid forum threads from people doing the jobs you want.',
  },
  {
    name: 'CFA Program',
    provider: 'CFA Institute',
    type: 'Credential',
    group: 'Miscellaneous',
    url: 'https://www.cfainstitute.org/programs/cfa',
    free: false,
    blurb: 'The gold-standard credential for investment analysis and portfolio management. Three rigorous exams that signal serious commitment to the buy side.',
  },
];
