// lib/learnResources.js
// Curated learning library for MERIDIAN LEARN (/learn).
// Structure by SECTION: Books | Resources | Podcasts | Miscellaneous.
// Each item: { name, provider, type, group, url, blurb, free }
//   group : Books | Resources | Podcasts | Miscellaneous
//   type  : Book | Site | Blog | Channel | Newsletter | Podcast | Tool | Data | Community | Credential | Reference
// Editorial rule: only things worth recommending. No paid courses we do not stand behind.
// Book links point to Amazon search (always resolves to the exact title).
// SYNTAX RULE: any string value containing an apostrophe MUST use DOUBLE quotes, or the build breaks.

export const GROUPS = ['Books', 'Courses', 'Resources', 'Podcasts', 'Miscellaneous'];

export const RESOURCES = [
  // ============================ COURSES ============================
  // Top-university courses, free to audit / genuinely free. The calibre we would
  // actually point a friend to -- not the paid course mills.
  {
    name: 'Introduction to Corporate Finance',
    provider: 'Wharton (UPenn) -- Coursera',
    type: 'Course',
    group: 'Courses',
    url: 'https://www.coursera.org/learn/wharton-finance',
    free: true,
    blurb: "Wharton's own intro to corporate finance with Prof. Michael Roberts: time value of money, cost of capital, capital budgeting and DCF. Free to audit.",
  },
  {
    name: 'Private Equity and Venture Capital',
    provider: 'Bocconi -- Coursera',
    type: 'Course',
    group: 'Courses',
    url: 'https://www.coursera.org/learn/private-equity',
    free: true,
    blurb: "Bocconi's flagship on how PE and VC really work -- fund structures, deals and value creation, taught by Stefano Caselli. Free to enroll.",
  },
  {
    name: 'Financial Markets',
    provider: 'Yale -- Coursera',
    type: 'Course',
    group: 'Courses',
    url: 'https://www.coursera.org/learn/financial-markets-global',
    free: true,
    blurb: 'Nobel laureate Robert Shiller on how markets, risk and institutions actually work. A modern classic, and free to audit.',
  },
  {
    name: 'Corporate Finance (full online class)',
    provider: 'Aswath Damodaran -- NYU Stern',
    type: 'Course',
    group: 'Courses',
    url: 'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/webcastfoundationsonline.htm',
    free: true,
    blurb: "The dean of valuation's full corporate finance class -- 12 short webcasts with slides. Completely free, no sign-up.",
  },
  {
    name: 'Valuation (full online class)',
    provider: 'Aswath Damodaran -- NYU Stern',
    type: 'Course',
    group: 'Courses',
    url: 'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/webcastvalonline.htm',
    free: true,
    blurb: '25 webcasts covering an entire semester of valuation -- DCF, multiples and real options -- with downloadable slides. Free.',
  },

  // ============================ BOOKS ============================
  {
    name: 'The Intelligent Investor',
    provider: 'Benjamin Graham',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=the+intelligent+investor+benjamin+graham',
    free: false,
    blurb: 'The value-investing bible that shaped Warren Buffett. Timeless on margin of safety, "Mr. Market", and the gap between price and value.',
  },
  {
    name: 'Security Analysis',
    provider: 'Graham & Dodd',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=security+analysis+graham+dodd',
    free: false,
    blurb: 'The 1934 foundation text of fundamental analysis. Dense, demanding and still the deepest treatment of what a security is really worth.',
  },
  {
    name: 'Common Stocks and Uncommon Profits',
    provider: 'Philip A. Fisher',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=common+stocks+and+uncommon+profits+fisher',
    free: false,
    blurb: 'The classic case for growth investing and qualitative research. Fisher on how to judge management, moats and durable competitive advantage.',
  },
  {
    name: 'The Little Book of Valuation',
    provider: 'Aswath Damodaran',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=the+little+book+of+valuation+damodaran',
    free: false,
    blurb: 'The friendliest way in to valuation. Short and practical, and honest about where the numbers come from and where they break.',
  },
  {
    name: 'Investment Valuation',
    provider: 'Aswath Damodaran',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=investment+valuation+damodaran',
    free: false,
    blurb: 'The comprehensive reference on valuing anything, from high-growth tech to distressed assets. The book professionals keep on the desk.',
  },
  {
    name: 'Investment Banking: Valuation, LBOs & M&A',
    provider: 'Rosenbaum & Pearl',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=investment+banking+rosenbaum+pearl',
    free: false,
    blurb: 'The industry standard on comps, precedent transactions, DCF and LBO analysis, laid out the way analysts are actually trained to build them.',
  },
  {
    name: 'Barbarians at the Gate',
    provider: 'Burrough & Helyar',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=barbarians+at+the+gate+burrough+helyar',
    free: false,
    blurb: 'The definitive story of the RJR Nabisco buyout. The best way to feel how ego, leverage and negotiation drive a mega-deal.',
  },
  {
    name: 'King of Capital',
    provider: 'Carey & Morris',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=king+of+capital+blackstone+carey+morris',
    free: false,
    blurb: 'The rise of Blackstone and modern private equity. Essential for understanding how buyout firms raise, deploy and return capital across cycles.',
  },
  {
    name: "Liar's Poker",
    provider: 'Michael Lewis',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=liars+poker+michael+lewis',
    free: false,
    blurb: "Michael Lewis's insider account of 1980s Salomon Brothers. Funny, sharp, and the book that made a generation want to trade bonds.",
  },
  {
    name: 'The Big Short',
    provider: 'Michael Lewis',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=the+big+short+michael+lewis',
    free: false,
    blurb: 'How a handful of outsiders saw the 2008 mortgage collapse coming. The clearest explanation of CDOs, CDS and structured credit gone wrong.',
  },
  {
    name: 'When Genius Failed',
    provider: 'Roger Lowenstein',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=when+genius+failed+lowenstein',
    free: false,
    blurb: 'The rise and fall of Long-Term Capital Management. A masterclass in leverage, model risk and how the smartest people blow up.',
  },
  {
    name: 'More Money Than God',
    provider: 'Sebastian Mallaby',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=more+money+than+god+mallaby',
    free: false,
    blurb: 'The definitive history of hedge funds and the people who built them. Great on strategy, edge, and where returns actually come from.',
  },
  {
    name: 'The Snowball',
    provider: 'Alice Schroeder',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=the+snowball+warren+buffett+schroeder',
    free: false,
    blurb: 'The authorised life of Warren Buffett. The closest thing to watching how a great capital allocator actually thinks, deal by deal.',
  },
  {
    name: 'Valuation: Measuring and Managing the Value of Companies',
    provider: 'McKinsey & Company (Koller, Goedhart, Wessels)',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=valuation+measuring+and+managing+the+value+of+companies+mckinsey',
    free: false,
    blurb: 'The McKinsey classic and gold standard of corporate valuation for over 30 years. Rigorous frameworks and worked cases for valuing any business, from stable incumbents to high-growth and digital.',
  },
  {
    name: 'Damodaran on Valuation',
    provider: 'Aswath Damodaran',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=damodaran+on+valuation',
    free: false,
    blurb: "Damodaran's deep treatment of security analysis for investing and corporate finance -- intrinsic value, relative valuation and the judgement behind the models.",
  },
  {
    name: 'Applied Mergers and Acquisitions',
    provider: 'Robert F. Bruner',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=applied+mergers+and+acquisitions+bruner',
    free: false,
    blurb: 'A rigorous, practical one-volume treatment of M&A: valuation, deal design, negotiation and the trade-offs that make or break a transaction.',
  },
  {
    name: 'Mergers, Acquisitions, and Corporate Restructurings',
    provider: 'Patrick A. Gaughan',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=mergers+acquisitions+and+corporate+restructurings+gaughan',
    free: false,
    blurb: 'A comprehensive survey of M&A and restructuring -- forms, motives, takeover defenses and the law behind them -- grounded in data and real case studies.',
  },
  {
    name: 'Financial Statement Analysis',
    provider: 'Fridson & Alvarez',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=financial+statement+analysis+fridson+alvarez',
    free: false,
    blurb: "A practitioner's guide to reading past the numbers: how to scrutinise financial statements and spot the reality behind reported earnings.",
  },
  {
    name: 'The Little Book of Common Sense Investing',
    provider: 'John C. Bogle',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=the+little+book+of+common+sense+investing+bogle',
    free: false,
    blurb: "The Vanguard founder's case for low-cost index investing -- the simplest, most durable advice most investors will ever need.",
  },
  {
    name: 'The Little Book That Beats the Market',
    provider: 'Joel Greenblatt',
    type: 'Book',
    group: 'Books',
    url: 'https://www.amazon.com/s?k=the+little+book+that+beats+the+market+greenblatt',
    free: false,
    blurb: "Greenblatt's 'magic formula' for buying good businesses at cheap prices, explained simply enough for anyone to follow.",
  },

  // ========================== RESOURCES ==========================
  {
    name: 'Damodaran Online',
    provider: 'NYU Stern',
    type: 'Site',
    group: 'Resources',
    url: 'https://pages.stern.nyu.edu/~adamodar/',
    free: true,
    blurb: 'A treasure chest: free valuation spreadsheets, current industry datasets and the full valuation class, all downloadable. The best free finance site online.',
  },
  {
    name: 'Aswath Damodaran (YouTube)',
    provider: 'NYU Stern',
    type: 'Channel',
    group: 'Resources',
    url: 'https://www.youtube.com/channel/UCLvnJL8htRR1T9cbSccaoVw',
    free: true,
    blurb: 'The "Dean of Valuation" posts his full NYU corporate-finance and valuation lectures for free. The single best place to actually learn valuation.',
  },
  {
    name: 'Musings on Markets',
    provider: 'Aswath Damodaran',
    type: 'Blog',
    group: 'Resources',
    url: 'https://aswathdamodaran.blogspot.com/',
    free: true,
    blurb: "Damodaran's long-running blog, where he values the biggest names and market stories of the moment in real time, and shows all his work.",
  },
  {
    name: 'Investopedia',
    provider: 'Investopedia',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.investopedia.com/',
    free: true,
    blurb: 'The free encyclopedia of finance. Look up any term you meet in a deal or on the tape, from EBITDA to mezzanine, with clear worked examples.',
  },
  {
    name: 'Khan Academy: Finance',
    provider: 'Khan Academy',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.khanacademy.org/economics-finance-domain/core-finance',
    free: true,
    blurb: 'Free, plain-English lessons that build the mental model: interest, bonds, equities, options and how the pieces of capital markets fit together.',
  },
  {
    name: 'Mergers & Inquisitions',
    provider: 'Brian DeChesare',
    type: 'Blog',
    group: 'Resources',
    url: 'https://mergersandinquisitions.com/',
    free: true,
    blurb: 'The most candid writing on how investment-banking and private-equity careers really work: roles, recruiting, exits and what the job is like.',
  },
  {
    name: 'Macabacus',
    provider: 'Macabacus',
    type: 'Site',
    group: 'Resources',
    url: 'https://macabacus.com/',
    free: true,
    blurb: 'A free best-practice reference for Excel and financial modeling. The place to tighten up your formatting, structure and model discipline.',
  },
  {
    name: 'Oaktree Memos',
    provider: 'Howard Marks',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.oaktreecapital.com/insights/memos',
    free: true,
    blurb: "Howard Marks's free memos on cycles, risk and market psychology. Buffett has said he reads them the day they arrive. So should you.",
  },
  {
    name: 'Berkshire Hathaway Shareholder Letters',
    provider: 'Warren Buffett',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.berkshirehathaway.com/letters/letters.html',
    free: true,
    blurb: "Warren Buffett's annual letters, free and archived for decades. Plain-English wisdom on business quality, valuation and capital allocation -- a free MBA in investing.",
  },
  {
    name: 'J.P. Morgan Guide to the Markets',
    provider: 'J.P. Morgan Asset Management',
    type: 'Reference',
    group: 'Resources',
    url: 'https://am.jpmorgan.com/us/en/asset-management/institutional/insights/market-insights/guide-to-the-markets/',
    free: true,
    blurb: 'A free quarterly chartbook of the global economy and markets. The clearest single source of the data every investor should have at hand.',
  },
  {
    name: 'Eye on the Market',
    provider: 'Michael Cembalest, J.P. Morgan',
    type: 'Newsletter',
    group: 'Resources',
    url: 'https://am.jpmorgan.com/us/en/asset-management/institutional/insights/market-insights/eye-on-the-market/',
    free: true,
    blurb: "Michael Cembalest's sharp, data-rich notes on markets, economics, energy and policy -- one of the most respected free reads on the Street.",
  },
  {
    name: 'Morgan Stanley Insights',
    provider: 'Morgan Stanley',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.morganstanley.com/insights',
    free: true,
    blurb: "Free research and the 'Thoughts on the Market' series from Morgan Stanley's strategists on what is driving markets right now.",
  },
  {
    name: 'Goldman Sachs Insights',
    provider: 'Goldman Sachs',
    type: 'Site',
    group: 'Resources',
    url: 'https://www.goldmansachs.com/insights',
    free: true,
    blurb: "Goldman Sachs's public research and briefings on markets, dealmaking and the global economy, written for a general audience.",
  },
  {
    name: 'BIS Quarterly Review',
    provider: 'Bank for International Settlements',
    type: 'Reference',
    group: 'Resources',
    url: 'https://www.bis.org/quarterlyreviews/index.htm',
    free: true,
    blurb: "The central bankers' bank on international banking and financial markets. Deep, free analysis of the plumbing of global finance.",
  },
  {
    name: 'IMF World Economic Outlook',
    provider: 'International Monetary Fund',
    type: 'Reference',
    group: 'Resources',
    url: 'https://www.imf.org/en/publications/weo',
    free: true,
    blurb: "The IMF's twice-yearly survey and projections for the world economy -- the reference point for global growth, inflation and risk.",
  },
  {
    name: 'Leveraged Finance 101: A Covenant Handbook',
    provider: 'Simpson Thacher & Bartlett',
    type: 'Reference',
    group: 'Resources',
    url: 'https://www.stblaw.com/docs/default-source/publications/leveraged-finance-101---a-covenant-handbook.pdf',
    free: true,
    blurb: 'A free law-firm handbook that decodes leveraged loan and high-yield covenant packages in plain English -- the deal-document side of LevFin most guides skip.',
  },
  {
    name: 'Leveraged Loan Primer',
    provider: 'PitchBook | LCD',
    type: 'Reference',
    group: 'Resources',
    url: 'https://pitchbook.com/leveraged-commentary-data/leveraged-loan-primer',
    free: true,
    blurb: 'The canonical free primer on the leveraged loan market: how deals are structured, syndicated, rated and traded. The standard first read on LevFin.',
  },
  {
    name: '2026 Leveraged Finance Outlook',
    provider: 'PineBridge Investments',
    type: 'Reference',
    group: 'Resources',
    url: 'https://www.pinebridge.com/en/insights/2026-leveraged-finance-outlook',
    free: true,
    blurb: "A current read on where leveraged credit is heading -- PineBridge's '90/10' view of a market splitting between stable performers and stressed, restructuring-bound names.",
  },

  // ========================== PODCASTS ==========================
  {
    name: 'Odd Lots',
    provider: 'Bloomberg',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.bloomberg.com/oddlots',
    free: true,
    blurb: 'Tracy Alloway and Joe Weisenthal unpack whatever is moving markets that week, from commodities to credit, with the people who actually know.',
  },
  {
    name: 'Acquired',
    provider: 'Gilbert & Rosenthal',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.acquired.fm/',
    free: true,
    blurb: 'Feature-length deep dives into the companies and deals that shaped the economy. Superb on strategy, moats and how value compounds over decades.',
  },
  {
    name: 'Invest Like the Best',
    provider: 'Patrick OShaughnessy',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://colossus.com/series/invest-like-the-best/',
    free: true,
    blurb: 'Long conversations with world-class investors and operators about how they find edge, allocate capital and think about risk.',
  },
  {
    name: 'Founders',
    provider: 'David Senra',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.founderspodcast.com/',
    free: true,
    blurb: 'Deep readings of the biographies of the great entrepreneurs and capital allocators of history, distilled into lessons you can use.',
  },
  {
    name: 'Money Stuff: The Podcast',
    provider: 'Bloomberg',
    type: 'Podcast',
    group: 'Podcasts',
    url: 'https://www.bloomberg.com/podcasts/series/money-stuff',
    free: true,
    blurb: 'Matt Levine and Katie Greifeld talk through the week in finance weirdness. The audio companion to the newsletter, just as entertaining.',
  },

  // ======================== MISCELLANEOUS ========================
  {
    name: 'Money Stuff',
    provider: 'Matt Levine, Bloomberg',
    type: 'Newsletter',
    group: 'Miscellaneous',
    url: 'https://www.bloomberg.com/account/newsletters/money-stuff',
    free: true,
    blurb: 'The best finance newsletter in the world, and free. Matt Levine makes Wall Street, M&A and market plumbing genuinely funny and genuinely clear.',
  },
  {
    name: 'FT Due Diligence',
    provider: 'Financial Times',
    type: 'Newsletter',
    group: 'Miscellaneous',
    url: 'https://www.ft.com/due-diligence',
    free: false,
    blurb: "The FT's insider briefing on M&A, private equity and dealmaking. The morning read for people who work on transactions.",
  },
  {
    name: 'Axios Pro Rata',
    provider: 'Dan Primack',
    type: 'Newsletter',
    group: 'Miscellaneous',
    url: 'https://www.axios.com/newsletters/axios-pro-rata',
    free: true,
    blurb: "Dan Primack's fast daily brief on deals, venture capital and private equity. Short, sharp and consistently ahead of the pack.",
  },
  {
    name: 'PETITION',
    provider: 'PETITION LLC',
    type: 'Newsletter',
    group: 'Miscellaneous',
    url: 'https://petition.substack.com/',
    free: true,
    blurb: 'The essential read on corporate distress, restructuring and bankruptcy. Irreverent, deeply informed, and early on where credit stress is building.',
  },
  {
    name: 'SEC EDGAR',
    provider: 'U.S. SEC',
    type: 'Tool',
    group: 'Miscellaneous',
    url: 'https://www.sec.gov/edgar/search/',
    free: true,
    blurb: 'Every US public filing, free: 10-Ks, 8-Ks, merger proxies and S-1s. Learn to read the primary source instead of the second-hand summary.',
  },
  {
    name: 'Koyfin',
    provider: 'Koyfin',
    type: 'Tool',
    group: 'Miscellaneous',
    url: 'https://www.koyfin.com/',
    free: true,
    blurb: 'A generous free tier for market data, screening and charting. A practical stand-in for a Bloomberg terminal while you learn.',
  },
  {
    name: 'TradingView',
    provider: 'TradingView',
    type: 'Tool',
    group: 'Miscellaneous',
    url: 'https://www.tradingview.com/',
    free: true,
    blurb: 'Fast, free charting for equities, rates, FX and crypto. Handy for tracking the price action behind the headlines you read here.',
  },
  {
    name: 'Damodaran Datasets',
    provider: 'NYU Stern',
    type: 'Data',
    group: 'Miscellaneous',
    url: 'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/data.html',
    free: true,
    blurb: 'Free, regularly updated industry data: betas, margins, cost of capital and multiples by sector. The inputs your valuation models actually need.',
  },
  {
    name: 'Wall Street Oasis',
    provider: 'WSO',
    type: 'Community',
    group: 'Miscellaneous',
    url: 'https://www.wallstreetoasis.com/',
    free: true,
    blurb: 'The largest finance-careers community: interview guides, compensation data and candid forum threads from people doing the jobs you want.',
  },
  {
    name: 'CFA Program',
    provider: 'CFA Institute',
    type: 'Credential',
    group: 'Miscellaneous',
    url: 'https://www.cfainstitute.org/programs/cfa',
    free: false,
    blurb: 'The gold-standard credential for investment analysis and portfolio management. Three rigorous exams that signal serious commitment to the buy side.',
  },
];
